version: '3.3'

services:

  app:
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - SASS_PATH=node_modules:src
